site_name: Renesas RZ Linux Solutions
site_description: Start here to explore all available Linux solutions for Renesas RZ Family.
site_url: https://renesas-rz.github.io/rz_solution
site_author: Renesas Electronics Corporation

repo_name: rz_solution
repo_url: https://github.com/renesas-rz/rz_solution

nav:
  # - Guidelines: guidelines/index.md
  - Home: index.md
  - Policy: policy/index.md

theme:
  name: material
  custom_dir: docs/_themes
  favicon: assets/icons/6723.T.png
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.integrate
    - toc.follow
  nav_top:
    # logos:
    #   - assets/icons/board.svg
    #   - assets/icons/ai_sdk.svg
    # btn:
    #   name: Get the Board
    #   url: download/
  palette:
    primary: custom

copyright: '&copy;2025, 2026 Renesas Electronics Corporation.'

extra:
  # announcements will be over-written from docs/_announcements/announcements.md (markdown)
  # ignore this
  announcements:
    # the following line is displayed in the announcement bar
    # keep length under 164 characters (less HTML tags) to fit on 1280px desktop window
    - '<b>Announcement!</b> RZ/G2L BSP Plus v1.0, RZ/G2L Ubuntu Support v1.0.0 and RZ/G2L Debian Support v1.0.0 are available.'
  announcements_urls:
    - available: '#whats-new'
  header_link: true
  footer_link:
    - link: legal_notices/
      name: Notices & Terms
      new_tab: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/renesas-rz
      name: Renesas RZ Software on GitHub
    - icon: fontawesome/solid/house
      link: https://www.renesas.com/
      name: Go to Renesas.com website
  # version:
  #   provider: mike
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/tablesort.js

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - markdown_grid_tables
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  # search must be in the top one
  - search
  - exclude:
      glob:
        - _*
        # - guidelines/_*/*
        - guidelines/*
        - download/_*/*
        - history/_*/*
        - home/_*
        - home/*.md
  - glightbox
  - include-markdown
  # - mkdocs-video
  - minify_html:
      keep_closing_tags: true
      keep_html_and_head_opening_tags: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
      js_files:
          - assets/javascripts/tablesort.js
      css_files:
          - assets/stylesheets/extra.css
  - table-reader
  # macros must be in the bottom one
  - macros

hooks:
  - mkdocs_event_hook.py
